services:

  # NGINX Web server (and naxsi as WAF)
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 443:443
    depends_on:
      - hypertube_backend
    volumes:
      - ./hypertube_apps/frontend/dist:/usr/share/nginx/html:ro
    networks:
      - hypertube-network

  # POSTGRES database
  # postgres:
  #   build: ./postgres
  #   container_name: postgres
  #   env_file:
  #     - ./postgres/.env
  #   volumes:
  #     - ./postgres/postgres-init:/postgres-init
  #     - ./postgres/data:/var/lib/postgres/data
  #   networks:
  #     - hypertube-network

  # Hypertube backend
  hypertube_backend:
    build: ./hypertube_apps/backend
    container_name: hypertube_backend
    ports:
      - 8000:8000
    volumes:
      - ./hypertube_apps/backend/app:/app
    # depends_on:
    #   - postgres
    networks:
      - hypertube-network
      
networks:
  hypertube-network:
    driver: bridge