services:

  # NGINX Web server (and naxsi as WAF)
  # Also contains the frontend static files
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    env_file: .env
    depends_on:
     - react_dev
     - hypertube_backend
    networks:
      - hypertube-network
    restart: on-failure

  react_dev:
    build: ./app/frontend
    container_name: react_dev
    env_file: .env
    volumes:
      - ./app/frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - hypertube-network
    restart: on-failure

  # Hypertube backend
  hypertube_backend:
    build: ./app/backend
    container_name: hypertube_backend
    ports:
      - 8000:8000
    env_file: .env
    volumes:
      - ./app/backend/app:/app
    depends_on:
      - mariadb
    networks:
      - hypertube-network
    restart: on-failure

  torrent_search_api:
    build: ./torrent_search_api
    container_name: torrent_search_api
    ports:
      - 3001:3001
    networks:
      - hypertube-network
    restart: on-failure

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    env_file: .env
    volumes:
      - ./mariadb/data:/var/lib/mysql
    networks:
      - hypertube-network
    restart: on-failure

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: on-failure
    # volumes:
    #     - ./data:/data
    ports:
        - 8025:8025
        - 1025:1025
    environment:
        MP_MAX_MESSAGES: 5000
        # MP_DATABASE: /data/mailpit.db
        MP_SMTP_AUTH_ACCEPT_ANY: 1
        MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - hypertube-network

networks:
  hypertube-network:
    driver: bridge